name: Test and Lint
on:
  push:
    branches:
      - "main"
    
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint and Vet
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.19

        - name: Tidy Up the Downloads
          run: |
            go mod tidy
        - name: Test
          run: make test